services:
  - type: web
    name: collab-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 16.20.0
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: "true"
